### ISSUE TITLE
Is this plugin still supported?

### ISSUE THREAD

**Issue by pinksharpii** [Nekmo/djangocms-comments#12]
This is the only comments plugin I'm seeing for Django CMS. But I can't even install it. It looks like I might need to downgrade pip to install according to a stackoverflow article??

I'm getting:

> File "/private/var/folders/r7/8n5l_mfd1qq74sq2f2nnxzx80000gn/T/pip-install-DKYgvU/djangocms-comments/setup.py", line 4, in <module> from pip.req import parse_requirements
>  ImportError: No module named req
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r7/8n5l_mfd1qq74sq2f2nnxzx80000gn/T/pip-install-DKYgvU/djangocms-comments/

**Comment by Nekmo** [comment]
Hello, I have not continued the maintenance of this plugin. I do not know if it works with the latest versions of DjangoCMS but I can fix this error.

**Comment by ZippoLag** [comment]
Hi!

I just sent a PR ( #13 ) with a fix for the install problem :)

**Comment by Nekmo** [comment]
Thanks @ZippoLag :)
