### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by jhonvidal** [Nekmo/djangocms-comments#2]
![keyerror at -es-quienes-somos- - google chrome_011](https://cloud.githubusercontent.com/assets/1105101/14612445/ffa73900-0564-11e6-9ef8-f2fcb13028ad.png)

my configurations:

``` javascript
INSTALLED_APPS = (
    ...,
    'djangocms_comments',
)

COMMENT_PUBLISHED_BY_DEFAULT = True
SPAM_PROTECTION = {} 
MIN_LENGTH_COMMENT_BODY = 50
MAX_LENGTH_COMMENT_BODY = 12000
MAX_BREAKLINES_COMMENT_BODY = 12
MAX_UPPERCASE_RATIO_COMMENT_BODY = 0.3
COMMENT_TEXTAREA_ROWS = 4
COMMENT_WAIT_SECONDS = 120
COMMENT_PREVENT_USURP_USERNAME = True


for var_name, value in dict(locals()).items():
    if var_name.isupper():
        locals()[var_name] = getattr(settings, var_name, value)
```

help me, please

**Comment by jhonvidal** [comment]
KeyError: 'object' in  `python obj = context['object']`

cms_plugins.py

``` python

from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _

from djangocms_comments.forms import UnregisteredCommentForm, CommentForm
from djangocms_comments.views import get_form_class, get_is_user
from .models import Comments, Comment


class CommentsPlugin(CMSPluginBase):
    model = Comments
    render_template = "djangocms_comments/comments.html"
    cache = False

    def render(self, context, instance, placeholder):
        obj = context['object']
        request = context['request']
        ct = ContentType.objects.get_for_model(obj)
        context['comments'] = self.get_comments(request, obj, ct)
        initial = {
            'config_id': instance.config.pk,
            'page_type': ct.pk,
            'page_id': obj.pk,
        }
        context['form'] = get_form_class(request)(initial=initial)
        context['is_user'] = get_is_user(request)
        return super(CommentsPlugin, self).render(context, instance, placeholder)

    @staticmethod
    def get_comments(request, obj, ct=None):
        ct = ct or ContentType.objects.get_for_model(obj)
        comments = Comment.objects.filter(page_type=ct, page_id=obj.pk)
        if not getattr(request.user, 'is_staff', False):
            comments = comments.filter(published=True)
        return comments


plugin_pool.register_plugin(CommentsPlugin)

```

**Comment by Nekmo** [comment]
Hello jhonvidal, are you testing on a page? Djangocms-comments only been tested for use in an app (Aldryn-newsblog in my case). However, it should work on a page with a small modification.

I'm going to check that. Please wait a moment.

**Comment by Nekmo** [comment]
Okay, try it now.

https://github.com/Nekmo/djangocms-comments/commit/abd68aa7b5c6b95156c10e050437f96188d0a59b

EDIT: You don't need to copy the DjangoCMS-Comments settings file in your settings. Only overwrite what you need.

**Comment by jhonvidal** [comment]
he was himself, trying on a page, I would like to integrate this component djangocms_miblog https://github.com/Pyc0kw4k/djangocms_miblog,  which I am using

**Comment by Nekmo** [comment]
I have solved at the last commit.

You'll have to install it from Git because it's not in Pypi:

`pip install -e git+https://github.com/Nekmo/djangocms-comments.git#egg=djangocms-comments`

I'll send to Pipy when I write the tests.

**Comment by jhonvidal** [comment]
thank you very much!, please check this component cms django blog is very interesting and very easy to use, how to integrate it?

**Comment by Nekmo** [comment]
Do you ask how to integrate Django CMS-Comments?
1. Go to "structure" in your page, click in "+" in the section. Search "Comments plugin".
   ![amazon_xenoblade10](https://cloud.githubusercontent.com/assets/740106/14619269/f632815c-05b6-11e6-9e7b-f915e106bc09.png)
2. Create a new config:
   ![amazon_xenoblade10](https://cloud.githubusercontent.com/assets/740106/14619290/1a590aa6-05b7-11e6-98dd-0dc9e066c0ec.png)
3. Save. It's done! :)

The blog system I use is "Aldryn-NewsBlog".

However, I will prove that you say to see if it works in DjangoCMS-Comments.

**Comment by jhonvidal** [comment]
very thanks !

**Comment by Nekmo** [comment]
The new release 0.1.3 fixes this.

Please understand that Django CMS-Comments are under development.

Thanks for your understanding!
